# Se a base 'Iris' for escolhida, alterar o arquivo irisConfiguration.yml,
# com base nas configurações desejadas

# chosen_base: 'Iris', 'Breast Cancer', 'Dermatology', 'Vertebral', 'XOR' , 'Artificial 1' ;
# neuron_type: Indica o neurônio utilizado na rede, pode ser 'P' para Perceptron, 'H' para
#              neurônio com função de ativação hiperbólica e 'L' neurônio com função de ati-
#              vação logística;
# realizations: Número máximo de realizações;
# epochs: Número máximo de épocas;
# learning_rate: Taxa de aprendizado;
# test_size: Porcentagem da base de teste.
# criterion_choose: indica o critério de escolha da melhor realização:
#                      1 para a melhor;
#                      2 para a mais próxima da acurácia;
#                      3 para a pior;


chosen_base: 'XOR'
realizations: 20
epochs: 200
initial_learning_rate: 0.5
final_learning_rate: 0.1
test_size: 0.2
criterion_choiced: 1
