# Se a base 'Iris' for escolhida, alterar o arquivo irisConfiguration.yml,
# com base nas configurações desejadas
# chosen_base: 'Iris' ou 'Artificial';
# realizations: Número máximo de realizações;
# epochs: Número máximo de épocas;
# learning_rate: Taxa de aprendizado;
# test_size: Porcentagem da base de teste.

chosen_base: 'Artificial'
realizations: 20
epochs: 100
learning_rate: 0.3
test_size: 0.2
