# features: atributos a serem considerados para a base,
#           podem ser escolhidos: 'sepal length (cm)',
#                                 'sepal width (cm)',
#                                 'petal length (cm)',
#                                 'petal width (cm)';

features:
          #- 'sepal length (cm)'
          - 'sepal width (cm)'
          #- 'petal length (cm)'
          - 'petal width (cm)'
